### ISSUE TITLE
TestCaseFilter support

### ISSUE THREAD

**Issue by MrGPT** [machine/machine.vstestadapter#15]
Is there a way to use the Test Case Filter in the TFS Build Definition to selectively run MSPEC test cases?

If so, could someone provide the Test Case Filter syntax as well as a sample of decorated code?

Thanks!

**Comment by ivanz** [comment]
It's not supported, but could be implemented. What would you be filtering on in your case?

**Comment by jonathh21** [comment]
Hi guys - I was literally about to raise a new issue for what I believe is this same case.

We use to be able to pass in a filter into vstest, but that filter doesn't appear to work anymore. 

Ivan, this is since the per assembly change worked on?

How hard do you think it would be to implement?

**Comment by jonathh21** [comment]
In terms of filters, it is whatever vstest supports, so test category, class name etc.

/TestCaseFilter:"TestCategory=Nightly|FullyQualifiedName=Namespace.ClassName.MethodName"

so this is currently being ignored.

**Comment by ivanz** [comment]
You will have to get the filter from the `IRunContext` at [MspecTestAdapterExecutor.cs#L21](https://github.com/machine-visualstudio/machine.vstestadapter/blob/master/Source/Machine.VSTestAdapter/MspecTestAdapterExecutor.cs#L21) and map it to MSpec's `RunOptions` ( [RunOptions.cs](https://github.com/machine/machine.specifications/blob/master/Source/Machine.Specifications/Runner/RunOptions.cs) ) to be passed in here [AppDomainExecutor.cs#L44](https://github.com/machine-visualstudio/machine.vstestadapter/blob/master/Source/Machine.VSTestAdapter/Execution/AppDomainExecutor.cs#L44)

**Comment by ivanz** [comment]
Moved to https://github.com/machine/machine.specifications/issues/327
