### ISSUE TITLE
Test runner doesn't appear to be doing anything - VS 2012 Pro

### ISSUE THREAD

**Issue by Andycharalambous** [machine/machine.vstestadapter#21]
Hi

I'm not sure whats happening, but I installed this VS addin and it's enabled, but no MSpec tests are ever picked up for running and it doesn't even appear that the test adapter is even running (no logging of any kind is visible in the output tab). When I use the NUnit test adapter I can see it working in the output tab - it logs info about discovering unit tests etc. I have tried disabling other addins - such as the aforementioned nunit test adaptor but still nothing seems to happen. I have uninstalled and re-installed with no difference. What am I doing wrong :)

I can run my specs fine from the command line using mspec.exe

**Comment by JonathanWilkins** [comment]
I'll have to have a look I haven't tested the adapter in VS 2012

**Comment by Andycharalambous** [comment]
Any word on this? I've just updated to v2.0.0.78 and I'm still not seeing anything different - no spec tests visible in Test Explorer.

**Comment by Andycharalambous** [comment]
I have both NUnit VS Adapter and this adapter installed but I only ever see this in the Tests output pane:

------ Load Playlist started ------
========== Load Playlist finished (0:00:00) ==========
------ Discover test started ------
NUnit VS Adapter 2.0.0.0 discovering tests is started
NUnit VS Adapter 2.0.0.0 discovering test is finished
========== Discover test finished: 241 found (0:00:04.5252605) ==========

**Comment by Andycharalambous** [comment]
Some more information - it would appear that VS doesn't think the extension is installed - even though all the files are present in my AppData\Local\Microsoft\VisualStudio\11.0\Extentions folder and the VSIX install log also bears this out - for what its worth my VS is 2012 Ultimate edition:

C:\Program Files (x86)\Microsoft Visual Studio 11.0>vstest.console.exe /listdiscoverers /UseVsixExtensions:true
Microsoft (R) Test Execution Command Line Tool Version 11.0.60315.1
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Test Discovery Add-Ins are available:
    Microsoft.VisualStudio.TestPlatform.Extensions.GenericTestAdapter.GenericTestDiscoverer
        Default Executor Uri: executor://generictestadapter/v1
        Supported File Types: .generictest
    Microsoft.VisualStudio.TestPlatform.Extensions.MSAppContainerAdapter.MSAppContainerTestDiscoverer
        Default Executor Uri: executor://msappcontainertestadapter/v1
        Supported File Types: .dll, .appx, .exe
    Microsoft.VisualStudio.TestPlatform.Extensions.OrderedTestAdapter.OrderedTestDiscoverer
        Default Executor Uri: executor://orderedtestadapter/v1
        Supported File Types: .orderedtest
    Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MSTestDiscoverer
        Default Executor Uri: executor://mstestadapter/v1
        Supported File Types: .dll, .exe
    Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestDiscoverer
        Default Executor Uri: executor://cppunittestexecutor/v1
        Supported File Types: .dll
    NUnit.VisualStudio.TestAdapter.NUnitTestDiscoverer
        Default Executor Uri: executor://nunittestexecutor/
        Supported File Types: .dll, .exe

**Comment by ivanz** [comment]
I am not sure what is happening here, but the fact that it can't find the adapter potentially indicates that it fails to load the adapter assembly?

One potential thing to try is:

1. Find the `Microsoft.VisualStudio.TestPlatform.ObjectModel.dll` in your Visual Studio installation
2. Replace the one in the Extensions folder
3. Check if it works and let us know.

**Comment by rsking** [comment]
I'm having the same issue with VS2013 Premium, not tests are found. The Discovery never describes mspec, and the output from `vstest.console.exe /listdiscoverers /UseVsixExtensions:true` never returns the mspec TestAdapter. Have tried both replacing and removing the Microsoft.VisualStudio.TestPlatform.ObjectModel in the adapter directory. Running ProcMon on the console test above does reveal that Machine.TestAdapter.dll is being scanned. Could this be an issue with the fact that the TestPlatform.ObjectModel is for VS2015?

**Comment by rsking** [comment]
Indeed, after recompiling the extension binding against either the VS11 or VS12 `Microsoft.VisualStudio.TestPlatform.ObjectModel.dll` the test adapter then loads and runs correctly. I would think that you need to link against the lowest VS version that you will support.

**Comment by ivanz** [comment]
Thanks for spending time investigating this. If we ship an older `Microsoft.VisualStudio.TestPlatform.ObjectModel.dll` I think some features wont' work in VS2015 (traits/tags) and might lead to errors when running tests in CI (VSTS/TS). I am not really sure what the right solution is here to be honest and I can't find much information on handling versioning of that assembly. Most people seem to be hardcoding a version of it. 

One possibility would be to change the build pipeline to produce VSIX builds for VS11/VS12 and publish a separate package? That would mean patching the path to the .dll as part of the build I am open to alternative suggestions?

**Comment by rsking** [comment]
Had a look at the NUnit adapter, and it does not distribute `Microsoft.VisualStudio.TestPlatform.ObjectModel.dll`, and binds against the VS11 version. I've tried removing the DLL from the extensions folder, and it uses the one contained in the TestWindow folder (verified using ProcMon.exe). I presume that the test manager has some sort of binding redirects going on to make sure that the latest version is being used, regardless of what has been bound to. I would think that the fact that we can still bind to the VS11 version means that it's not directly using any VS2015 specific APIs, so it should be safe.

**Comment by ivanz** [comment]
Closing as fixed. 2.2.2 of the nuget package binds to the 11.0.0.0 version of the assembly when targeting .net framework (and 15.0.0.0 when targeting .NET core)
