### ISSUE TITLE
Can't load Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=14.0.0.0

### ISSUE THREAD

**Issue by adenhertog** [machine/machine.vstestadapter#57]
All of our tests broke after the switch to 2.0.0 with this LoaderException and we had to roll back to 1.7.0.6.

**Comment by ivanz** [comment]
How and where do you run the tests and what is the installed Visual Studio version?

**Comment by ivanz** [comment]
Any errors relating to version mismatch of this assembly should be fixed in 2.2.2 of the nuget package
