### ISSUE TITLE
Release 2.1.0 to Visual Studio Gallery

### ISSUE THREAD

**Issue by ivanz** [machine/machine.vstestadapter#62]
Hey @JonathanWilkins - sorry to bug you, but could you please upload the new vsix to the gallery whenever you have some time: https://github.com/machine/machine.vstestadapter/releases/download/v2.1.0/Machine.VSTestAdapter.VSIX.vsix

@molszews I've released the NuGet one to NuGet.org. Thanks for the contribution.

**Comment by JonathanWilkins** [comment]
Sure no problem

**Comment by JonathanWilkins** [comment]
All sorted
