### ISSUE TITLE
Ensure 2.4.0 doesn't break backwards compatability

### ISSUE THREAD

**Issue by ivanz** [machine/machine.vstestadapter#66]
- [x] VS Solution with a Test project using mspec 0.11 and runner 2.4.0-x works
- [x] VS Solution with a Test project using mspec 0.12 and runner 2.4.0-x works
- [x] VS Solution with a Test project using mspec 0.12 and runner 2.3.0 works

**Comment by robertcoltheart** [comment]
Will get on this tomorrow. 👍

**Comment by robertcoltheart** [comment]
mspec 0.12 and runner 2.3.0 works. 👍

**Comment by robertcoltheart** [comment]
Ok, gone through the above and it all seems to work as expected.

**Comment by ivanz** [comment]
Feel free to update the release config and tag v2.4.0 to push the nuget out if you are happy with everything on the Reshaped runner side. 👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
