### ISSUE TITLE
Visual Studio Gallery

### ISSUE THREAD

**Issue by JonathanWilkins** [machine/machine.vstestadapter#67]
@ivanz Do uou want me to release an new version to the Gallery? I see that has fallen behind quiet a bit. Or should I just direct them to the Nuget Gallery version.

Cheers
Jonathan

**Comment by robertcoltheart** [comment]
I don't see the point. VS 2017 uses nuget now, and there hasn't been any fundamental changes to mspec in a while that would warrant an update for VS '15 or lower, unless I'm mistaken. The VSIX is not part of the solution right now either, so we aren't even building it on Appveyor.

**Comment by JonathanWilkins** [comment]
Sure no problem, What I'll do is put a comment on the gallery that if anyone wants an update or VS2017 support they must use the Nuget version.
