### ISSUE TITLE
Can't update to 2.3.0 via NuGet

### ISSUE THREAD

**Issue by UniSnake** [machine/machine.vstestadapter#70]
Error is "Unable to find a version of 'Mono.Cecil' that is compatible with 'Machine.Specifications.Runner.VisualStudio 2.3.0 constraint: Mono.Cecil (>= 0.10.0-beta6)'."

2.4.0 has the same issue.

My target is .NET Framework 4.7 x64

**Comment by UniSnake** [comment]
By allowing pre-releases I was able to get that dependency. Had to manually add the reference though.

**Comment by ivanz** [comment]
Thanks for reporting. I am Re-opening in order to see if the experience could be improved. I think for new style projects this doesn't happen but if it does for old style projects then maybe we can target .Net Framework with the previous stable version of Mono Cecil

**Comment by robertcoltheart** [comment]
@UniSnake Please use 2.5.1 and let me know if this resolves this issue?

**Comment by UniSnake** [comment]
Yes, I was able to upgrade to 2.5.1 without issue. Thank you!
