### ISSUE TITLE
Conflict with Microsoft.Azure.DocumentDB

### ISSUE THREAD

**Issue by UniSnake** [machine/machine.vstestadapter#72]
After adding a reference to NuGet package Microsoft.Azure.DocumentDB 1.17.0 to my test project, and using it in a test, tests stop showing up with the error 'Exception has been thrown by the target of an invocation.' Tests still show up using the ReSharper test runner extension.

**Comment by ivanz** [comment]
Can you please share a small repro project to allow us to debug the issue?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by UniSnake** [comment]
In the process of creating the repro project I discovered it was an error on our end (putting initialization code in a test class constructor instead of using Establish).
