### ISSUE TITLE
Slow test discovery for large projects

### ISSUE THREAD

**Issue by bjuris** [machine/machine.vstestadapter#74]
Discovering 2,000 contexts takes several minutes since the assembly definition is re-loaded from Cecil for every context.

When fixing this our test discovery measured via "dotnet test -t --no-build" went from several minutes to a few seconds.

**Comment by ivanz** [comment]
Fixed in v2.5.2  - https://github.com/machine/machine.vstestadapter/releases/tag/v2.5.2

Should show up on NuGet shortly.

**Comment by bjuris** [comment]
Great, that was fast.
