### ISSUE TITLE
Unable to navigate to source code through test items in Test Explorer？

### ISSUE THREAD

**Issue by Y2zz** [machine/machine.vstestadapter#82]
Hello, @robertcoltheart  I found a small problem, but I am not sure if it belongs to mspec.

I can't navigate to the source code through the test item in the VS2017 Test Explorer. I uploaded a sample project.

https://github.com/Y2zz/Machine.vstestadapter-problem-demo/blob/master/test/Acme.PhoneBook.Tests/Mspec/Test.cs

You can get the code by https://github.com/Y2zz/Machine.vstestadapter-problem-demo

**Comment by robertcoltheart** [comment]
You have an error in the constructor of the file `MspecTestBase` that is causing the test discovery to fail. If you switch to "Tests" in your output window, you will see the test discovery failing.
