### ISSUE TITLE
nuget package has dependency on Microsoft.NETCore.App 

### ISSUE THREAD

**Issue by lust4life** [machine/machine.vstestadapter#83]
https://www.nuget.org/packages/Machine.Specifications.Runner.VisualStudio

hi, from link above, it show this package has a dependency on `Microsoft.NETCore.App (>= 1.1.2)` , not sure if this is a issues from `machine.vstestadapter`, but from https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#recommendations , it seems that we'd better not have this package dependency ? 

Do you know how this be generated ?

**Comment by robertcoltheart** [comment]
I think this is because we are using the csproj to pack the nuget package, and using netcoreapp1.1. We should probably upgrade it to netcoreapp2.1 or 2.2.
